// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8c2wAuabyiTOAbMLt2VG6gH3SvDUqpLU',
    appId: '1:824517917959:web:e044c8bdea8dfd32d999a2',
    messagingSenderId: '824517917959',
    projectId: 'heyyou-d3a84',
    authDomain: 'heyyou-d3a84.firebaseapp.com',
    storageBucket: 'heyyou-d3a84.firebasestorage.app',
    measurementId: 'G-ZMVF7FHNRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3JXFOkq4PwZwM8QqYTPb_g7gPDoIc2c',
    appId: '1:824517917959:android:a93e6fec8fa461b1d999a2',
    messagingSenderId: '824517917959',
    projectId: 'heyyou-d3a84',
    storageBucket: 'heyyou-d3a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQ-MsRZP8zJI6SJ4_pjHA_vW5lkzUImE',
    appId: '1:824517917959:ios:150678f968754744d999a2',
    messagingSenderId: '824517917959',
    projectId: 'heyyou-d3a84',
    storageBucket: 'heyyou-d3a84.firebasestorage.app',
    iosBundleId: 'com.heyyou.heyYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8c2wAuabyiTOAbMLt2VG6gH3SvDUqpLU',
    appId: '1:824517917959:web:4ee14780fae91f3dd999a2',
    messagingSenderId: '824517917959',
    projectId: 'heyyou-d3a84',
    authDomain: 'heyyou-d3a84.firebaseapp.com',
    storageBucket: 'heyyou-d3a84.firebasestorage.app',
    measurementId: 'G-6MNQ2B510K',
  );
}
